spring:
    profiles:
        active:
            - dev
---
server:
  port: 8001
  profiles: dev
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application: #定义为服务的名字，作为日后负载均衡使用
    name: microcloud-provider-product
logging:
  level:
    cn.enjoy.mapper: debug
eureka:
  client: #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://admin:mysqladmin@eureka1:7001/eureka
  instance:
    instance-id: microcloud-provider-product:8001 #页面显示主机信息时显示的信息
    prefer-ip-address: true #访问路径换为ip地址
    #lease-expiration-duration-in-seconds: 5 #如果5秒不跳表示挂了(默认是90秒)
    #lease-renewal-interval-in-seconds: 2 #设置心跳的间隔（默认是30秒）
info:
  app.name: mldn-microcloud
  compay.name: www.mldn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
  profiles: beta
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application: #定义为服务的名字，作为日后负载均衡使用
    name: microcloud-provider-product
logging:
  level:
    cn.enjoy.mapper: debug
eureka:
  client: #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://admin:mysqladmin@eureka1:7001/eureka
  instance:
    instance-id: microcloud-provider-product:8001 #页面显示主机信息时显示的信息
    prefer-ip-address: true #访问路径换为ip地址
    #lease-expiration-duration-in-seconds: 5 #如果5秒不跳表示挂了(默认是90秒)
    #lease-renewal-interval-in-seconds: 2 #设置心跳的间隔（默认是30秒）
info:
  app.name: mldn-microcloud
  compay.name: www.mldn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$