spring:
    profiles:
        active:
            - dev
---
spring:
    port: 8201
    profiles: dev
    application:
        name: microcloud-config-client 
eureka:
  client: 
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka
---
spring:
    port: 8202
    profiles: beta
    application:
        name: microcloud-config-client 
eureka:
  client: 
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka