server:
  port: 8107

spring:
  application: #定义为服务的名字，作为日后负载均衡使用
    name: microcloud-provider-dept
logging:
  level:
    cn.enjoy.mapper: debug
eureka:
  client: #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  instance:
    instance-id: microcloud-provider-dept:8101 #页面显示主机信息时显示的信息
    prefer-ip-address: true #访问路径换为ip地址
    #lease-expiration-duration-in-seconds: 5 #如果5秒不跳表示挂了(默认是90秒)
    #lease-renewal-interval-in-seconds: 2 #设置心跳的间隔（默认是30秒）
info:
  app.name: mldn-microcloud
  compay.name: www.mldn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
management:
  endpoints:
    web:
      exposure:
        include: "*"
